name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
         
      - name: Build with Gradle
        run: ./gradlew testDebug assemble
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS:  ${{ secrets.KEY_ALIAS }}
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: greetings.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
